# Form implementation generated from reading ui file 'Part1gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(318, 535)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(60, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(240, 60, 61, 21))
        self.submit_button.setObjectName("submit_button")
        self.input_Score = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_Score.setGeometry(QtCore.QRect(120, 60, 111, 20))
        self.input_Score.setObjectName("input_Score")
        self.input_Name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_Name.setGeometry(QtCore.QRect(0, 60, 111, 20))
        self.input_Name.setObjectName("input_Name")
        self.choose_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.choose_button.setGeometry(QtCore.QRect(190, 100, 61, 21))
        self.choose_button.setObjectName("choose_button")
        self.candidate_opt_drpdwn = QtWidgets.QComboBox(parent=self.centralwidget)
        self.candidate_opt_drpdwn.setGeometry(QtCore.QRect(20, 100, 141, 21))
        self.candidate_opt_drpdwn.setObjectName("candidate_opt_drpdwn")
        self.candidate_opt_drpdwn.addItem("")
        self.checkBoxCandidate2 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxCandidate2.setEnabled(True)
        self.checkBoxCandidate2.setGeometry(QtCore.QRect(180, 140, 111, 21))
        self.checkBoxCandidate2.setObjectName("checkBoxCandidate2")
        self.checkBoxCandidate3 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxCandidate3.setEnabled(True)
        self.checkBoxCandidate3.setGeometry(QtCore.QRect(180, 170, 111, 31))
        self.checkBoxCandidate3.setObjectName("checkBoxCandidate3")
        self.generate_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generate_button.setEnabled(True)
        self.generate_button.setGeometry(QtCore.QRect(100, 210, 91, 31))
        self.generate_button.setFlat(False)
        self.generate_button.setObjectName("generate_button")
        self.checkBoxCandidate4 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxCandidate4.setEnabled(True)
        self.checkBoxCandidate4.setGeometry(QtCore.QRect(10, 170, 111, 31))
        self.checkBoxCandidate4.setObjectName("checkBoxCandidate4")
        self.checkBoxCandidate1 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxCandidate1.setEnabled(True)
        self.checkBoxCandidate1.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.checkBoxCandidate1.setObjectName("checkBoxCandidate1")
        self.output_section = QtWidgets.QLabel(parent=self.centralwidget)
        self.output_section.setGeometry(QtCore.QRect(10, 250, 291, 221))
        self.output_section.setText("")
        self.output_section.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_section.setObjectName("output_section")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 318, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "Welcome to Lab 2 Grade Estimate"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))
        self.input_Score.setPlaceholderText(_translate("MainWindow", "Enter a Score"))
        self.input_Name.setPlaceholderText(_translate("MainWindow", "Enter a Name"))
        self.choose_button.setText(_translate("MainWindow", "CHOOSE"))
        self.candidate_opt_drpdwn.setCurrentText(_translate("MainWindow", "Candidate"))
        self.candidate_opt_drpdwn.setItemText(0, _translate("MainWindow", "Candidate"))
        self.checkBoxCandidate2.setText(_translate("MainWindow", "Candidate 2"))
        self.checkBoxCandidate3.setText(_translate("MainWindow", "Candidate 4"))
        self.generate_button.setText(_translate("MainWindow", "Generate"))
        self.checkBoxCandidate4.setText(_translate("MainWindow", "Candidate 3"))
        self.checkBoxCandidate1.setText(_translate("MainWindow", "Candidate 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
